# Generated by Django 4.2.6 on 2023-11-07 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Bike',
                'verbose_name_plural': 'Bikes',
            },
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('type', models.TextField(choices=[('Bike', 'Bicycle'), ('Car', 'Car'), ('Any', 'Any')])),
            ],
            options={
                'verbose_name': ('Brand',),
                'verbose_name_plural': 'Brands',
            },
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=50)),
                ('brand', models.ManyToManyField(to='app.brand')),
            ],
            options={
                'verbose_name': ('Car',),
                'verbose_name_plural': 'Cars',
            },
        ),
        migrations.CreateModel(
            name='Depot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('capacity', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'Depot',
                'verbose_name_plural': 'Depots',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('isSubscribed', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': ('User',),
                'verbose_name_plural': 'Users',
            },
        ),
        migrations.CreateModel(
            name='Rent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rentBike', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.bike')),
                ('rentCar', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.car')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user')),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='depot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.depot'),
        ),
        migrations.AddField(
            model_name='bike',
            name='brand',
            field=models.ManyToManyField(to='app.brand'),
        ),
        migrations.AddField(
            model_name='bike',
            name='depot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.depot'),
        ),
    ]
