# Generated by Django 4.2.6 on 2023-11-07 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bike',
            options={'verbose_name': 'Велосипед', 'verbose_name_plural': 'Велосипеды'},
        ),
        migrations.AlterModelOptions(
            name='brand',
            options={'verbose_name': ('Бренд',), 'verbose_name_plural': 'Бренды'},
        ),
        migrations.AlterModelOptions(
            name='car',
            options={'verbose_name': ('Автомобиль',), 'verbose_name_plural': 'Автомобили'},
        ),
        migrations.AlterModelOptions(
            name='depot',
            options={'verbose_name': 'Депо', 'verbose_name_plural': 'Депо'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': ('Пользователь',), 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AddField(
            model_name='bike',
            name='costDaily',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bike',
            name='costPerHour',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bike',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.user'),
        ),
        migrations.AddField(
            model_name='car',
            name='costDaily',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='car',
            name='costPerHour',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='car',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.user'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='type',
            field=models.TextField(choices=[('Велосипед', 'Bicycle'), ('Автомобиль', 'Car'), ('Любое транспортное средство', 'Any')]),
        ),
        migrations.DeleteModel(
            name='Rent',
        ),
    ]
