# Generated by Django 4.2.6 on 2023-11-08 10:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0004_bike_owner_car_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bike',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='car',
            name='owner',
        ),
        migrations.CreateModel(
            name='Rent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(default=django.utils.timezone.now)),
                ('end', models.DateTimeField(null=True)),
                ('is_finished', models.BooleanField(default=False)),
                ('final_price', models.PositiveIntegerField(default=0)),
                ('Bike', models.ManyToManyField(to='app.bike')),
                ('Car', models.ManyToManyField(to='app.car')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': ('Аренда',),
                'verbose_name_plural': 'Аренды',
            },
        ),
        migrations.AddField(
            model_name='bike',
            name='rents',
            field=models.ManyToManyField(to='app.rent'),
        ),
        migrations.AddField(
            model_name='car',
            name='rents',
            field=models.ManyToManyField(to='app.rent'),
        ),
    ]
