# Generated by Django 4.2.6 on 2023-11-08 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_bike_owner_remove_car_owner_rent_bike_rents_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bike',
            name='rents',
        ),
        migrations.RemoveField(
            model_name='car',
            name='rents',
        ),
    ]
